import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Types } from 'mongoose';

import type { PaymentPurpose, PaymentStatus } from '@ruletka/shared-types';

/** Provider enum — only CloudPayments is supported (mirrors `paymentProviderSchema`). */
const PROVIDERS = ['cloudpayments'] as const;
/** Payment lifecycle states (mirrors `paymentStatusSchema`). */
const STATUSES: readonly PaymentStatus[] = ['pending', 'completed', 'failed', 'refunded'];
/** What the payment buys (mirrors `paymentPurposeSchema`). */
const PURPOSES: readonly PaymentPurpose[] = ['coins', 'premium'];

/**
 * A single CloudPayments money movement.
 *
 * `invoiceId` is generated by us per checkout and is UNIQUE — it is the
 * idempotency key for the whole flow: webhooks (`Pay`/`Fail`/`Refund`) are
 * looked up by it, and double-deliveries are detected by the already-terminal
 * `status`. We never trust client-sent amounts; `amount` is fixed from the
 * server-side coin-package / plan price at checkout time.
 *
 * `rawPayload` keeps the last provider notification verbatim for audit/dispute
 * (no card data is ever present — PAN/CVV stay inside the CloudPayments widget).
 */
@Schema({ collection: 'payments', timestamps: { createdAt: true, updatedAt: true } })
export class Payment {
  /** Paying account. */
  @Prop({ required: true, type: Types.ObjectId, ref: 'User' })
  userId!: Types.ObjectId;

  /** Payment provider (always `cloudpayments`). */
  @Prop({ required: true, enum: PROVIDERS, default: 'cloudpayments', type: String })
  provider!: (typeof PROVIDERS)[number];

  /** Our unique invoice id (idempotency key). Unique index declared below. */
  @Prop({ required: true, type: String })
  invoiceId!: string;

  /** CloudPayments transaction id, set once a notification references it. */
  @Prop({ required: false, default: null, type: Number })
  transactionId!: number | null;

  /** CloudPayments recurring-charge token (premium subscriptions), if any. */
  @Prop({ required: false, default: null, type: String })
  subscriptionToken!: string | null;

  /** CloudPayments subscription id (recurrent), if any. */
  @Prop({ required: false, default: null, type: String })
  subscriptionId!: string | null;

  /** Charged amount in `currency` (server-fixed; never from the client). */
  @Prop({ required: true, type: Number, min: 0 })
  amount!: number;

  /** ISO 4217 currency. Coins/premium are priced in RUB. */
  @Prop({ required: true, default: 'RUB', type: String })
  currency!: string;

  /** Lifecycle state. */
  @Prop({ required: true, enum: STATUSES, default: 'pending', type: String })
  status!: PaymentStatus;

  /** What the payment buys. */
  @Prop({ required: true, enum: PURPOSES, type: String })
  purpose!: PaymentPurpose;

  /** Coin-package code (for `purpose: 'coins'`). */
  @Prop({ required: false, default: null, type: String })
  packageCode!: string | null;

  /** Premium plan code (for `purpose: 'premium'`). */
  @Prop({ required: false, default: null, type: String })
  plan!: string | null;

  /** Last raw provider notification (audit). Never contains card data. */
  @Prop({ required: false, default: null, type: Object })
  rawPayload!: Record<string, unknown> | null;

  // `createdAt` / `updatedAt` are added by `timestamps`.
}

export type PaymentDocument = HydratedDocument<Payment>;

export const PaymentSchema = SchemaFactory.createForClass(Payment);

// ── Indexes (PROJECT_SPEC §6) ──────────────────────────────────────────────
// Idempotency: one row per invoice, and the primary webhook lookup key.
PaymentSchema.index({ invoiceId: 1 }, { unique: true });
// Provider transaction lookups (idempotency for Confirm/Refund by tx id).
// UNIQUE + PARTIAL: an invoice ↔ CloudPayments transaction is 1:1, DB-enforced.
// `transactionId` DEFAULTS to explicit `null` (see @Prop above), so a `sparse`
// index would NOT help — sparse only excludes ABSENT fields, not explicit-null
// ones, so the many `pending`/unmatched rows would all carry `null` and COLLIDE
// on the unique key (E11000 → syncIndexes aborts boot). A `partialFilterExpression`
// matching the field's actual BSON type (`transactionId` is a Number) constrains
// uniqueness to rows that actually carry a provider tx id and lets every
// null/unmatched row sit outside the index entirely.
PaymentSchema.index(
  { transactionId: 1 },
  { unique: true, partialFilterExpression: { transactionId: { $type: 'number' } } },
);
// A user's payment history, newest first.
PaymentSchema.index({ userId: 1, createdAt: -1 });
